
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascrip
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build 
        
      displayName: 'npm install, build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '.'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: deloy
  displayName: deploy stage
  jobs:
   - deployment: VMDeploy
     displayName: web
     environment:
       name: node-env
       resourceType: VirtualMachine
     strategy:
          rolling:
            maxParallel: 2
            preDeploy:
              steps:
              - download: current
                artifact: drop
              - script: echo initialize, cleanup, backup, install certs
            deploy:
              steps:
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |
                   sudo cp -a /home/azureuser/azagent/_work/1/drop/./ /var/www/html 
            routeTraffic:
                steps:
                - script: echo routing traffic
            postRouteTraffic:
                steps:
                - script: echo health check post-route traffic
            on:
             failure:
              steps:
              - script: echo Restore from backup! This is on failure
             success:
              steps:
              - script: echo Notify! This is on success
